interface ISwitch {
	id: number
  nameSwitch: string
}

export interface ISectionsSwitch {
  	styleHair: ISwitch[]
	freckles: ISwitch[]
	diseasesSkin: ISwitch[]
	colorEye: ISwitch[]
	hair: ISwitch[]
	eyebrow: ISwitch[]
}

export const switchData: ISectionsSwitch[] = [
	{
		styleHair: [
			{ id: 1, nameSwitch: 'Стиль прически #1' },
			{ id: 2, nameSwitch: 'Стиль прически #2' },
			{ id: 3, nameSwitch: 'Стиль прически #3' },
			{ id: 4, nameSwitch: 'Стиль прически #4' },
			{ id: 5, nameSwitch: 'Стиль прически #5' },
			{ id: 6, nameSwitch: 'Стиль прически #6' },
			{ id: 7, nameSwitch: 'Стиль прически #7' },
		],
		freckles: [
			{ id: 1, nameSwitch: 'Веснушки #1' },
			{ id: 2, nameSwitch: 'Веснушки #2' },
			{ id: 3, nameSwitch: 'Веснушки #3' },
			{ id: 4, nameSwitch: 'Веснушки #4' },
			{ id: 5, nameSwitch: 'Веснушки #5' },
			{ id: 6, nameSwitch: 'Веснушки #6' },
			{ id: 7, nameSwitch: 'Веснушки #7' },
		],
		diseasesSkin: [
			{ id: 1, nameSwitch: 'Заболевание #1' },
			{ id: 2, nameSwitch: 'Заболевание #2' },
			{ id: 3, nameSwitch: 'Заболевание #3' },
			{ id: 4, nameSwitch: 'Заболевание #4' },
			{ id: 5, nameSwitch: 'Заболевание #5' },
			{ id: 6, nameSwitch: 'Заболевание #6' },
			{ id: 7, nameSwitch: 'Заболевание #7' },
			{ id: 8, nameSwitch: 'Заболевание #8' },
			{ id: 9, nameSwitch: 'Заболевание #9' },
			{ id: 10, nameSwitch: 'Заболевание #10' },
			{ id: 11, nameSwitch: 'Заболевание #11' },
		],
		colorEye: [
			{ id: 0, nameSwitch: "Зленый" },
			{ id: 1, nameSwitch: "Изумрудный" },
            { id: 2, nameSwitch: "Голубой" },
            { id: 3, nameSwitch: "Синий" },
            { id: 4, nameSwitch: "Светлый шатен" },
            { id: 5, nameSwitch: "Темно-коричневый" },
            { id: 6, nameSwitch: "Карий" },
            { id: 7, nameSwitch: "Темно-серый" },
            { id: 8, nameSwitch: "Светло-серый" },
            { id: 9, nameSwitch: "Розовый" },
            { id: 10, nameSwitch: "Желтый" },
            { id: 11, nameSwitch: "Фиолетовый" },
            { id: 12, nameSwitch: "Затемение" },
            { id: 13, nameSwitch: "Оттенки серого" },
            { id: 14, nameSwitch: "Текила-санрайз" },
            { id: 15, nameSwitch: "Атомный" },
            { id: 16, nameSwitch: "Искажение" },
            { id: 17, nameSwitch: "ECola" },
            { id: 18, nameSwitch: "Космический рейнджер" },
            { id: 19, nameSwitch: "Инь-ян" },
            { id: 20, nameSwitch: "Мишень" },
            { id: 21, nameSwitch: "Ящерица" },
            { id: 22, nameSwitch: "Дракон" },
            { id: 23, nameSwitch: "Инопланетянин" },
            { id: 24, nameSwitch: "Козел" },
            { id: 25, nameSwitch: "Смайлик" },
            { id: 26, nameSwitch: "Одержимый" },
            { id: 27, nameSwitch: "Демон" },
            { id: 28, nameSwitch: "Зараженный" },
            { id: 29, nameSwitch: "Пришелец" },
            { id: 30, nameSwitch: "Нежить" },
            { id: 31, nameSwitch: "Зомби" }

		],
		hair: [
			{ id: 0, nameSwitch: 'Прическа #1' },
			{ id: 1, nameSwitch: 'Прическа #2' },
			{ id: 2, nameSwitch: 'Прическа #3' },
			{ id: 3, nameSwitch: 'Прическа #4' },
			{ id: 4, nameSwitch: 'Прическа #5' },
			{ id: 5, nameSwitch: 'Прическа #6' },
			{ id: 6, nameSwitch: 'Прическа #7' },
			{ id: 7, nameSwitch: 'Прическа #8' },
			{ id: 8, nameSwitch: 'Прическа #9' },
			{ id: 9, nameSwitch: 'Прическа #10' },
			{ id: 10, nameSwitch: 'Прическа #11' },
			{ id: 11, nameSwitch: 'Прическа #12' },
			{ id: 12, nameSwitch: 'Прическа #13' },
			{ id: 13, nameSwitch: 'Прическа #14' },
			{ id: 14, nameSwitch: 'Прическа #15' },
			{ id: 15, nameSwitch: 'Прическа #16' },
			{ id: 16, nameSwitch: 'Прическа #17' },
			{ id: 17, nameSwitch: 'Прическа #18' },
			{ id: 18, nameSwitch: 'Прическа #19' },
			{ id: 19, nameSwitch: 'Прическа #20' },
			{ id: 20, nameSwitch: 'Прическа #21' },
			{ id: 21, nameSwitch: 'Прическа #22' },
			{ id: 22, nameSwitch: 'Прическа #23' },
			{ id: 23, nameSwitch: 'Прическа #24' },
			{ id: 24, nameSwitch: 'Прическа #25' },
			{ id: 25, nameSwitch: 'Прическа #26' },
			{ id: 26, nameSwitch: 'Прическа #27' },
			{ id: 27, nameSwitch: 'Прическа #28' },
			{ id: 28, nameSwitch: 'Прическа #29' },
			{ id: 29, nameSwitch: 'Прическа #30' },
			{ id: 30, nameSwitch: 'Прическа #31' },
			{ id: 31, nameSwitch: 'Прическа #32' },
			{ id: 32, nameSwitch: 'Прическа #33' },
			{ id: 33, nameSwitch: 'Прическа #34' },
			{ id: 34, nameSwitch: 'Прическа #35' },
			{ id: 35, nameSwitch: 'Прическа #36' },
			{ id: 36, nameSwitch: 'Прическа #37' },
			{ id: 37, nameSwitch: 'Прическа #38' },
			{ id: 38, nameSwitch: 'Прическа #39' },
			{ id: 39, nameSwitch: 'Прическа #40' },
			{ id: 40, nameSwitch: 'Прическа #41' },
			{ id: 41, nameSwitch: 'Прическа #42' },
			{ id: 42, nameSwitch: 'Прическа #43' },
			{ id: 43, nameSwitch: 'Прическа #44' },
			{ id: 44, nameSwitch: 'Прическа #45' },
			{ id: 45, nameSwitch: 'Прическа #46' },
			{ id: 46, nameSwitch: 'Прическа #47' },
			{ id: 47, nameSwitch: 'Прическа #48' },
			{ id: 48, nameSwitch: 'Прическа #49' },
			{ id: 49, nameSwitch: 'Прическа #50' },
			{ id: 50, nameSwitch: 'Прическа #51' },
			{ id: 51, nameSwitch: 'Прическа #52' },
			{ id: 52, nameSwitch: 'Прическа #53' },
			{ id: 53, nameSwitch: 'Прическа #54' },
			{ id: 54, nameSwitch: 'Прическа #55' },
			{ id: 55, nameSwitch: 'Прическа #56' },
			{ id: 56, nameSwitch: 'Прическа #57' },
			{ id: 57, nameSwitch: 'Прическа #58' },
			{ id: 58, nameSwitch: 'Прическа #59' },
			{ id: 59, nameSwitch: 'Прическа #60' },
			{ id: 60, nameSwitch: 'Прическа #61' },
			{ id: 61, nameSwitch: 'Прическа #62' },
			{ id: 62, nameSwitch: 'Прическа #63' },
			{ id: 63, nameSwitch: 'Прическа #64' },
			{ id: 64, nameSwitch: 'Прическа #65' },
			{ id: 65, nameSwitch: 'Прическа #66' },
			{ id: 66, nameSwitch: 'Прическа #67' },
			{ id: 67, nameSwitch: 'Прическа #68' },
			{ id: 68, nameSwitch: 'Прическа #69' },
			{ id: 69, nameSwitch: 'Прическа #70' },
			{ id: 70, nameSwitch: 'Прическа #71' },
			{ id: 71, nameSwitch: 'Прическа #72' },
			{ id: 72, nameSwitch: 'Прическа #73' },
			{ id: 73, nameSwitch: 'Прическа #74' },

		],
		eyebrow: [
			{ id: 0, nameSwitch: 'Брови #1' },
			{ id: 1, nameSwitch: 'Брови #2' },
			{ id: 2, nameSwitch: 'Брови #3' },
			{ id: 3, nameSwitch: 'Брови #4' },
			{ id: 4, nameSwitch: 'Брови #5' },
			{ id: 5, nameSwitch: 'Брови #6' },
			{ id: 6, nameSwitch: 'Брови #7' },
			{ id: 7, nameSwitch: 'Брови #8' },
			{ id: 8, nameSwitch: 'Брови #9' },
			{ id: 9, nameSwitch: 'Брови #10' },
			{ id: 10, nameSwitch: 'Брови #11' },
			{ id: 11, nameSwitch: 'Брови #12' },
			{ id: 12, nameSwitch: 'Брови #13' },
			{ id: 13, nameSwitch: 'Брови #14' },
			{ id: 14, nameSwitch: 'Брови #15' },
			{ id: 15, nameSwitch: 'Брови #16' },
			{ id: 16, nameSwitch: 'Брови #17' },
			{ id: 17, nameSwitch: 'Брови #18' },
			{ id: 18, nameSwitch: 'Брови #19' },
			{ id: 19, nameSwitch: 'Брови #20' },
			{ id: 20, nameSwitch: 'Брови #21' },
			{ id: 21, nameSwitch: 'Брови #22' },
			{ id: 22, nameSwitch: 'Брови #23' },
			{ id: 23, nameSwitch: 'Брови #24' },
			{ id: 24, nameSwitch: 'Брови #25' },
			{ id: 25, nameSwitch: 'Брови #26' },
			{ id: 26, nameSwitch: 'Брови #27' },
			{ id: 27, nameSwitch: 'Брови #28' },
			{ id: 28, nameSwitch: 'Брови #29' },
			{ id: 29, nameSwitch: 'Брови #30' },
			{ id: 30, nameSwitch: 'Брови #31' },
			{ id: 31, nameSwitch: 'Брови #32' },
			{ id: 32, nameSwitch: 'Брови #33' },
			{ id: 33, nameSwitch: 'Брови #34' },
			{ id: 34, nameSwitch: 'Брови #35' },
			{ id: 35, nameSwitch: 'Брови #36' },
			{ id: 36, nameSwitch: 'Брови #37' },
			{ id: 37, nameSwitch: 'Брови #38' },
			{ id: 38, nameSwitch: 'Брови #39' },
			{ id: 39, nameSwitch: 'Брови #40' },
			{ id: 40, nameSwitch: 'Брови #41' },
			{ id: 41, nameSwitch: 'Брови #42' },
			{ id: 42, nameSwitch: 'Брови #43' },
			{ id: 43, nameSwitch: 'Брови #44' },
			{ id: 44, nameSwitch: 'Брови #45' },
			{ id: 45, nameSwitch: 'Брови #46' },
			{ id: 46, nameSwitch: 'Брови #47' },
			{ id: 47, nameSwitch: 'Брови #48' },
			{ id: 48, nameSwitch: 'Брови #49' },
			{ id: 49, nameSwitch: 'Брови #50' },
			{ id: 50, nameSwitch: 'Брови #51' },
			{ id: 51, nameSwitch: 'Брови #52' },
			{ id: 52, nameSwitch: 'Брови #53' },
			{ id: 53, nameSwitch: 'Брови #54' },
			{ id: 54, nameSwitch: 'Брови #55' },
			{ id: 55, nameSwitch: 'Брови #56' },
			{ id: 56, nameSwitch: 'Брови #57' },
			{ id: 57, nameSwitch: 'Брови #58' },
			{ id: 58, nameSwitch: 'Брови #59' },
			{ id: 59, nameSwitch: 'Брови #60' },
			{ id: 60, nameSwitch: 'Брови #61' },
			{ id: 61, nameSwitch: 'Брови #62' },
			{ id: 62, nameSwitch: 'Брови #63' },
			{ id: 63, nameSwitch: 'Брови #64' },
			{ id: 64, nameSwitch: 'Брови #65' },
			{ id: 65, nameSwitch: 'Брови #66' },
			{ id: 66, nameSwitch: 'Брови #67' },
			{ id: 67, nameSwitch: 'Брови #68' },
			{ id: 68, nameSwitch: 'Брови #69' },
			{ id: 69, nameSwitch: 'Брови #70' },
			{ id: 70, nameSwitch: 'Брови #71' },
			{ id: 71, nameSwitch: 'Брови #72' },
			{ id: 72, nameSwitch: 'Брови #73' },
			{ id: 73, nameSwitch: 'Брови #74' },
		],
	},
]